:zap: Major re-work of command handler (Automatic)
jw2476/AgeOfEternity pull request #2
Opened 2020-11-07 18:16 UTC by Townsy45

* :bug: Fixed bug with guildPrefix so now it should not error if the guildPrefix / guild does not exist in the database.

2020-11-07 18:30 UTC, jw2476 requested changes
The functions and variables need type hinting

2020-11-07 18:30 UTC, jw2476 commented on src/cmd/index.ts
> +        cmds.push(require(cmd.filePath).default);
You could instantiate the class here

2020-11-07 21:22 UTC, Townsy45 commented
I have moved where the classes are initialised but I disagree with the typing.

When I try to assign types to this is produces a lot of errors for stuff that actually works. It would be more work for no benefit.

Feel free to take a look yourself but you will have to rewrite most of it to fit specific typing.

2020-11-08 15:02 UTC, jw2476 commented
Not all of it needs to be typeed, only the functions returns and variables at the top of the file.

2020-11-08 20:06 UTC, jw2476 commented
@Townsy45 would you like me to make the changes? The command handler is really important and I'm more then happy to do it if you don't want to!

2020-11-13 00:28 UTC, closed without merging

2020-11-13 00:28 UTC, Townsy45 commented
Changing PR from Master => Beta